include: lint_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/l10n/intl/**
    - lib/**/generated/**
    - plugins/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    invalid_annotation_target: ignore
