name: fl_clash
description: A multi-platform proxy client based on ClashMeta, simple and easy to use, open-source and ad-free.
publish_to: 'none'
version: 0.8.96+2026081701
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.3
  window_manager:
    git:
      url: https://github.com/chen08209/window_manager
      ref: 5a489acfe5799c38909e3e96abd11b78354f1809
      path: packages/window_manager
  dynamic_color: ^1.9.0
  proxy:
    path: plugins/proxy
  window_ext:
    path: plugins/window_ext
  launch_at_startup:
    git:
      url: https://github.com/chen08209/launch_at_startup.git
      ref: e930ce65c5804343103447e01d39fccabedc8681
  json_annotation: ^4.12.0
  file_picker: ^12.0.0
  mobile_scanner: ^7.4.0
  app_links: ^7.1.2
  win32_registry: ^3.0.3
  tray:
    path: plugins/tray
  wifi_ssid:
    path: plugins/wifi_ssid
  collection: ^1.19.1
  animations: ^2.1.1
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2
  freezed_annotation: ^3.1.0
  image_picker: ^1.2.0
  ffi: ^2.1.4

  webdav_client: ^1.2.2
  dio: ^5.8.0+1
  win32: ^6.4.0
  re_editor: ^0.10.0
  re_highlight: ^0.0.3
  archive: ^4.0.7
  emoji_regex: ^0.0.5
  hotkey_manager: ^0.2.3
  uni_platform: ^0.1.3
  device_info_plus: ^13.2.0
  connectivity_plus: ^7.3.1
  screen_retriever: ^0.2.1
  defer_pointer: ^0.0.2
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  riverpod: ^3.3.2
  material_color_utilities: ^0.13.0
  flutter_js: ^0.8.7
  flutter_svg: ^2.1.0
  flutter_cache_manager: ^3.4.1
  crypto: ^3.0.3
  yaml_writer:
    git:
      url: https://github.com/chen08209/yaml_writer
      ref: 79c78a44ec9c2f5f5f97da1a65610c6fb2ead8b3
  super_sliver_list: ^0.4.1
  drift: ^2.34.3
  drift_flutter: ^0.3.1
  fractional_indexing: ^1.0.0
  reorderable_grid: ^1.0.13
  smooth_sheets: ^1.1.1
  rust_api:
    path: plugins/rust_api
  setup:
    path: plugins/setup
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.14.1
  build_runner: ^2.15.1
  args: ^2.4.2
  freezed: 3.2.6-dev.1
  riverpod_generator: ^4.0.4

  drift_dev: ^2.34.0
  intl_utils: ^2.8.15
  test: ^1.31.0
  sqlite3: ^3.5.1
  cross_file: ^0.3.4+2
  mocktail: ^1.0.4
  yaml: ^3.1.3
  path_provider_platform_interface: ^2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/avatar/
    - assets/images/empty/
    - assets/images/icon/
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: Twemoji
      fonts:
        - asset: assets/fonts/Twemoji.Mozilla.ttf
    - family: Icons
      fonts:
        - asset: assets/fonts/Icons.ttf
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: arb
  output_dir: lib/l10n
