display_name: flclash++

icon: ./assets/images/icon.png

keywords:
  - flclash++
  - Clash
  - ClashMeta
  - Proxy

generic_name: flclash++

categories:
  - Network

startup_notify: true

include: []
