display_name: FlClash

icon: ./assets/images/icon.png

supported_mime_type:
  - x-scheme-handler/clash
  - x-scheme-handler/clashmeta
  - x-scheme-handler/flclash

keywords:
  - FlClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash

categories:
  - Network

startup_notify: true

include: []