// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<RustFoldRange>> foldsComputeAll({
  required RopeBridge rope,
  required BigInt tabSize,
}) => RustLib.instance.api.crateApiEditorFoldsComputeAll(
  rope: rope,
  tabSize: tabSize,
);

BigInt? foldsFindMatchingBracket({
  required RopeBridge rope,
  required BigInt targetOffset,
}) => RustLib.instance.api.crateApiEditorFoldsFindMatchingBracket(
  rope: rope,
  targetOffset: targetOffset,
);

List<GuideBlock> guidesComputeViewport({
  required RopeBridge rope,
  required BigInt firstVisible,
  required BigInt lastVisible,
  required BigInt tabSize,
}) => RustLib.instance.api.crateApiEditorGuidesComputeViewport(
  rope: rope,
  firstVisible: firstVisible,
  lastVisible: lastVisible,
  tabSize: tabSize,
);

Future<List<String>> wordsExtract({required RopeBridge rope}) =>
    RustLib.instance.api.crateApiEditorWordsExtract(rope: rope);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RopeBridge>>
abstract class RopeBridge implements RustOpaqueInterface {
  List<String> cachedLinesRange({
    required BigInt startLine,
    required BigInt endLine,
  });

  BigInt charToLine({required BigInt charIdx});

  static RopeBridge create({required String initialText}) => RustLib
      .instance
      .api
      .crateApiEditorRopeBridgeCreate(initialText: initialText);

  String getText();

  void insert({required BigInt charIdx, required String text});

  BigInt lenChars();

  BigInt lenLines();

  String line({required BigInt lineIdx});

  BigInt lineToChar({required BigInt lineIdx});

  void remove({required BigInt start, required BigInt end});

  String slice({required BigInt start, required BigInt end});
}

class GuideBlock {
  final int startLine;
  final int endLine;
  final int indentLevel;
  final int leadingSpaces;

  const GuideBlock({
    required this.startLine,
    required this.endLine,
    required this.indentLevel,
    required this.leadingSpaces,
  });

  @override
  int get hashCode =>
      startLine.hashCode ^
      endLine.hashCode ^
      indentLevel.hashCode ^
      leadingSpaces.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuideBlock &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine &&
          indentLevel == other.indentLevel &&
          leadingSpaces == other.leadingSpaces;
}

class RustFoldRange {
  final int startLine;
  final int endLine;

  const RustFoldRange({required this.startLine, required this.endLine});

  @override
  int get hashCode => startLine.hashCode ^ endLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustFoldRange &&
          runtimeType == other.runtimeType &&
          startLine == other.startLine &&
          endLine == other.endLine;
}
