// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

Stream<int> hotKeyEvents() => RustLib.instance.api.crateApiHotkeyHotKeyEvents();

Future<List<HotKeyFailure>> setHotKeys({required List<HotKeySpec> specs}) =>
    RustLib.instance.api.crateApiHotkeySetHotKeys(specs: specs);

class HotKeyFailure {
  final int id;
  final String reason;

  const HotKeyFailure({required this.id, required this.reason});

  @override
  int get hashCode => id.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HotKeyFailure &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          reason == other.reason;
}

enum HotKeyModifier { alt, capsLock, control, fn, meta, shift }

class HotKeySpec {
  final int id;
  final int key;
  final List<HotKeyModifier> modifiers;

  const HotKeySpec({
    required this.id,
    required this.key,
    required this.modifiers,
  });

  @override
  int get hashCode => id.hashCode ^ key.hashCode ^ modifiers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HotKeySpec &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          key == other.key &&
          modifiers == other.modifiers;
}
