// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cleanup_socket`, `clear_shutdown_fd`, `io_loop`, `is_current_gen`, `make_frame`, `read_frame`, `save_shutdown_fd`, `shutdown_old_fd`, `write_frame`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ServerState`

Stream<Uint8List> restartIpcServer({required String name}) =>
    RustLib.instance.api.crateApiIpcRestartIpcServer(name: name);

Future<void> stopIpcServer() => RustLib.instance.api.crateApiIpcStopIpcServer();

Future<bool> ipcServerStatus() =>
    RustLib.instance.api.crateApiIpcIpcServerStatus();

Future<bool> isIpcConnected() =>
    RustLib.instance.api.crateApiIpcIsIpcConnected();

Future<void> sendIpcMessage({required List<int> data}) =>
    RustLib.instance.api.crateApiIpcSendIpcMessage(data: data);
