// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<Uint8List> restartIpcServer({required String name}) =>
    RustLib.instance.api.crateApiIpcRestartIpcServer(name: name);

Future<void> stopIpcServer() => RustLib.instance.api.crateApiIpcStopIpcServer();

Future<void> sendIpcMessage({required List<int> data}) =>
    RustLib.instance.api.crateApiIpcSendIpcMessage(data: data);
