// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Runs `main(config)` from a profile override script and returns the JSON the
/// script produced. `config` is the profile as JSON; the result replaces it.
Future<String> evaluateScript({
  required String script,
  required String config,
}) => RustLib.instance.api.crateApiScriptEvaluateScript(
  script: script,
  config: config,
);
